### ISSUE TITLE
Separate dev and prod

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/garden#119]
Currently there is only one instance of the Garden backend API. We would like there to be two. Similar to how we have the frontend repo set up, the default branch should auto-deploy to our dev environment. Then when we're satisfied with the changes we can promote the build to production by pushing the contents of the dev branch to a prod branch that triggers a production deploy.

# Assumptions:
1. There will be two git branches in the garden-backend repo that trigger deploys. One to the dev env, one to prod. Look at how the frontend repo is set up for inspiration.
2. All changes should be reflected in, and deployed by, our terraform.

# Acceptance Criteria
Given I am a Garden dev making a backend change, when I need to push up a change I can push up to dev first, and then test it out without impacting users on prod.

```[tasklist]
### Tasks
```

**Comment by WillEngler** [comment]
There's another ticket that covers test vs real data stores. Gonna scope this ticket to be making a separate dev and prod backend API

**Comment by OwenPriceSkelly** [comment]
friday update: the heavy lifting/refactoring is done for this, but in a terraform workspace that's isolated from our true backend. so we have the current untouched backend workspace with just prod and a sandbox workspace with the dev/prod split. All that's left is to swap in the new terraform so that the current backend becomes the prod side of the new one, sanity check that the GH actions flow does what we want, plus documenting/reviewing the changes etc. 

sprint planning tldr: very, very close to done. ok to pull it in to sprint 18 for me along with #154

**Comment by WillEngler** [comment]
Closed by https://github.com/Garden-AI/garden-backend/pull/36
