### ISSUE TITLE
Paper cut: It takes ~10 minutes to see if a pipeline works

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#138]
Registering a pipeline that uses Tensorflow and running it for the first time takes about 10 minutes. 6 or 7 minutes to register the pipeline, then 2-3 minutes to execute it the first time. If you are troubleshooting a pipeline, this makes your iteration loop pretty slow.

**Comment by blaiszik** [comment]
Not sure if this comment exactly fits here or not, but one thing that sometimes helps band-aid over such paper cuts is having clear status displayed to the user, especially with timing hints. If they can see e.g., "container building" or "container spinning up" notifications with some approximate time it might give them a hint to go grab a snack instead of stewing in front of the computer waiting.

**Comment by WillEngler** [comment]
For spinning up the container we show a little spinner and say "Building container. This operation times out after 30 minutes." And then we print the current build status every 30 seconds.

We could probably improve most on pipeline invocation. Right now it just has a spinner and it tells you it's executing remotely. We should probably have some more status indication there, especially for when it's doing a cold start.

**Comment by BenGalewsky** [comment]
This could just be caching of docker layers on the container service node. The very first repo2docker run on a node takes a very long time. Thereafter its quite quick
