### ISSUE TITLE
torch 2.0.1 fails to install dependent cuda libraries with poetry

### ISSUE THREAD

**Issue by MaxTuecke** [Garden-AI/garden#213]
Currently when trying to register torch models on ubuntu actions, Garden breaks with the error:

`ValueError: libnvrtc.so.*[0-9].*[0-9] not found in the system path`

This is due to torch 2.0.1 failing to install its cuda dependencies when installed with poetry on GPU enabled machines.

# Assumptions
1. Pytorch will resolve this issue before the next release after 2.0.1.

# Acceptance Criteria
Change the version for torch in poetry so it skips 2.0.1

**Comment by OwenPriceSkelly** [comment]
additional context: poetry fetches dependency info differently than pip would; the torch team uploaded distributions to pypi in such a way that breaks for poetry but not pip. It seems like is only a problem on linux when using poetry to install from pypi. The easiest thing for us to do is likely to just skip 2.0.1. 
- issue to watch https://github.com/pytorch/pytorch/issues/100974 in case they fix the metadata for 2.0.1 
- otherwise, looks like they have tests to catch this in the future https://github.com/pytorch/builder/pull/1419 so anything past 2.0.1 should be fine
