### ISSUE TITLE
Garden Publish

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#53]
_As a garden author I want to publish my garden so others can find it_

# Description
```
% garden-ai garden publish
```
Write a record to Globus Search

# Assumptions:
# Acceptance Criteria
Given..., when..., then...

**Comment by WillEngler** [comment]
Alternate description:

Of our 3 entities (gardens, pipelines, models) only pipelines have separate creation and publication steps. That's because pipelines are Python code, so creating a pipeline scaffolds some code and publishing pushes up that code and makes it executable.

So a description for `garden pipeline publish` follows ...

Publishing a pipeline should:
- parse the metadata in the Python pipeline file
- generate a local pipeline.json file from it
- mint a DOI for the pipeline if this is the initial publication
- invoke container creation (See #49)
- save a reference to the registered funcx function in the pipeline.json
