### ISSUE TITLE
minor code fixes

### ISSUE THREAD

**Issue by Aadit-Ambadkar** [Garden-AI/garden#58]
_There are some instances of code that can be changed to be better (they are not necessarily bad or syntactically wrong, just ... unpleasant?)_

# Assumptions:
1. https://github.com/Garden-AI/garden/blob/01f097543e97993d2e7133045ebcb967a6c58eaf/examples/toy_example.py#L73 change `+= [pea_edibility_pipeline]` to `.append(pea_edibility_pipeline)`
2. https://github.com/Garden-AI/garden/blob/01f097543e97993d2e7133045ebcb967a6c58eaf/examples/toy_example.py#L40-L41 there should be a line between these two lines
3. https://github.com/Garden-AI/garden/blob/01f097543e97993d2e7133045ebcb967a6c58eaf/examples/toy_example.py#L61 change `+= ["Friar Hugo", "Sister Constance"]` to `.extend(["Friar Hugo", "Sister Constance"])`

**Comment by Aadit-Ambadkar** [comment]
Leaving this here as a note, that the process of adding authors and pipelines should probably be changed such that `_sync_author_metadata` is called each time a Pipeline is added to a Garden model, or an Author is added to either.

**Comment by OwenPriceSkelly** [comment]
Hey Aadit, `toy_example` was originally just a gist I'd shared in slack, just there to demo the sdk's interface as it was progressing (and specifically hoping to elicit this kind of feedback -- which, thank you) :)
1. Is deliberate. we perform validation on assignment; mutating the value without assignment compromises that (see example in docstring for `Garden.validate`). 
2. Also deliberate. The comment is just another line of the 10ish lines of commentary preceding it, and I found that less clear when rereading after linting. Similar motivation in making the "problem code" part above it a docstring, rather than just line-commenting it. 
3. Again, we don't want or need to mutate these directly, especially when dealing with such small objects. It might even be a good idea to refactor and make these attributes tuples instead under the hood. Feel free to open a PR for that if you'd like :) 
4. invoking `_sync_author_metadata` on pipeline or author validation is a good idea! It's also exactly the sort of thing we can't do if we're mutating the list in-place. That also could make a good PR if you're fishing for one. 

As a side note, I'm guessing that the unpleasantness you're alluding to is because it seems like it'd be less performant, but you might be interested to note that `x += y` is not just syntax sugar for `x = x + y`. While the RHS of `x = x + y` would `x = type(x).__add__(x, y)` (which _is_ much slower than `list.append`); instead `x += y` becomes `type(x).__iadd__(x, y)` (which is negligibly slower than `list.append`). Take a look: 
<img width="645" alt="image" src="https://user-images.githubusercontent.com/21372141/217899728-1f8879e6-d002-43b9-985a-1c94de4026b4.png">
