### ISSUE TITLE
`_sync_author_metadata` whenever 

### ISSUE THREAD

**Issue by Aadit-Ambadkar** [Garden-AI/garden#59]
> invoking `_sync_author_metadata` on pipeline or author validation is a good idea! It's also exactly the sort of thing we can't do if we're mutating the list in place (without assignment).

My proposed solution is to sync the metadata in any function which uses the author or contributor metadata. What are your thoughts on this?

**Comment by OwenPriceSkelly** [comment]
I think that that would be one way to keep our author/contributor metadata consistent, but that seems a bit "brittle" to me -- e.g. suppose someone else opens a PR which implements "institutional affiliations" for the author/contributor metadata, they'd be writing methods which manipulate author or contributor metadata but (because it's someone else writing these) they don't remember to call `_sync_author_metadata` every time; IMO the best place to enforce this sync is whenever the `pipelines` attribute is assigned to (so you can't add a pipeline without triggering a sync). 

We're using the `pydantic` library under the hood, which gives us an easy way to do this -- these are the relevant docs https://docs.pydantic.dev/usage/validators/ -- and there are a few examples on the Garden/Pipeline/Step classes using the syntax already (just nothing for the `pipelines` attribute, yet)

**Comment by OwenPriceSkelly** [comment]
Also as a side note, the `cli-module-scaffolding` branch is the next one we're going to merge into main and it refactors things a bit -- if you get started before main is caught up, it might avoid a git-rebase-headache to start your new branch from that one rather than from main (not the end of the world either way though).

**Comment by Aadit-Ambadkar** [comment]
Would you recommend using root validators or just regular validators?

Also, it looks like validators don't run if an element is added to a list:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/58674441/218931425-754099a8-9af0-49be-88ea-562adf765aed.png">

**Comment by OwenPriceSkelly** [comment]
yep! that's exactly right, there are a few things we wanted to do with pydantic that aren't the default (and in my experience kind of hard to find in the docs), but I think that's the big one. For context, we wanted the ability to have "partial" Gardens -- e.g. `doi` is required _eventually_, but not known at creation time since we mint those using other required info, like authors/title.

all three of the Steps/Pipeline/Garden classes should already be configured to validate on assignment, iirc

**Comment by Aadit-Ambadkar** [comment]
It looks like there is another pr that's up for merging. Should I wait or start working on that?

**Comment by OwenPriceSkelly** [comment]
that one should be merged soon (hopefully today); probably easiest for you to start your new branch from the 46-garden-create-command branch rather than main if you started in the meantime

**Comment by Aadit-Ambadkar** [comment]
I don't see the 46-garden-create-command branch though...

**Comment by Aadit-Ambadkar** [comment]
Sounds good. I'm just tacking on a `@validator("pipelines")` right before the `_sync_author_metadata` definition in the `Garden` class, and `@validator("steps")` for the `Pipelines` class. that should work, I believe.

**Comment by isaac-darling** [comment]
Handled in the Garden class overhaul.
