### ISSUE TITLE
Spike: Model Versioning

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/garden#64]
Research what we want to do for model versioning

# Acceptance criteria
Some stories

**Comment by BenGalewsky** [comment]
Well, this is going to be easy since our model repository already supports this. We can even tag an arbitrary version number as _Production_ so pipelines can just refer to this logical version tag and always execute the version the model publisher has identified as current best. You can also pin your pipeline to a specific version number

**Comment by ascourtas** [comment]
Glorious

**Comment by OwenPriceSkelly** [comment]
I didn't see it documented anywhere outside of the actual mlflow code, but `models:/mymodel/latest` _does_ work without doing anything extra, unlike `models:/mymodel/production` which would need a specific version to be explicitly set as "Production" -- do we want to allow that behavior?

**Comment by WillEngler** [comment]
Closing as stale (or done?). Users can specify a model revision in the Hugging Face connector
