### ISSUE TITLE
Inference on a Large Model

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#74]
_As a garden user I want to perform inference on a large model so I can get exciting scientific results_

# Assumptions:
1. These models don't go into the model repository
2. The inference step will have an endpoint uuid instead of a model ID from the repository (or field in the model metadata)
3. User has to create an MLModel directory structure in their environment. Use the standard MLFlow.predict
4. We write a custom flavor to allow `predict` on the custom model (assuming it's not just a big PyTorch model, but something specific)
5. We have the support of Eli's group to assist
6. This is easy to do. If we find lots of "gotcha's" then this becomes a spike story and provide more detailed stories of how to eventually implement this

# Description
Instead of downloading the model just call the function on the specified endpoint. We can assume that the model is mounted in the endpoint

# Acceptance Criteria
Documentation on setting up a custom funcx endpoint, how to create the MLModel db and creating a custom MLModel flavor.

A reference implementation of AlphaFold on Delta with an associated endpoint

**Comment by BenGalewsky** [comment]
Actually even easier... it could be that the pipeline specifies the default FuncX Endpoint to run on and then the the inference step is nothing special. It can assume that the model lives in an expected place in the worker.

**Comment by OwenPriceSkelly** [comment]
got sidetracked the other day poking around the mlflow codebase and started thinking about this story, just writing down what I think might be the easy way to do this so I don't forget: we could have an analogue to `garden_ai.Model("me@uni.edu-mylocalmodel/2")` called like `garden_ai.LocalModel(...)`, which just un-sets `os.environ['MLFLOW_TRACKING_URI']` before calling `load_model`. That way, if the endpoint's `./mlruns` local directory looks like mlflow expects, `LocalModel` would make mlflow "download" models from `./mlruns` instead of our backend; we can decide later how to handle the case where the endpoint doesn't have everything it needs in the `./mlruns` local directory (e.g. trying to run the pipeline on an endpoint which doesn't have the model saved locally)

**Comment by OwenPriceSkelly** [comment]
while I'm at it: since this is for Eliu's AlphaFold model, we'll also probably need to implement a little alphafold mlflow model flavor (which will probably not be the hard part here)

**Comment by WillEngler** [comment]
Closing as stale. We'll probably revisit this soon
